version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: dbt-tutorial
      schema: jaffle_shop
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.

    - name: stripe
      description: This is a replica of the Stripe payments data.
      database: dbt-tutorial
      schema: stripe
      tables:
        - name: payment
          description: One record per payment transaction.